export const COUNTRIES: {
    pt: string;
    es: string;
    en: string;
    fr: string;
}[] = [
        { pt: 'Afeganistão', es: 'Afganistán', en: 'Afghanistan', fr: 'Afghanistan' },
        { pt: 'África do Sul', es: 'Sudáfrica', en: 'South Africa', fr: 'Afrique du Sud' },
        { pt: 'Albânia', es: 'Albania', en: 'Albania', fr: 'Albanie' },
        { pt: 'Alemanha', es: 'Alemania', en: 'Germany', fr: 'Allemagne' },
        { pt: 'Andorra', es: 'Andorra', en: 'Andorra', fr: 'Andorre' },
        { pt: 'Angola', es: 'Angola', en: 'Angola', fr: 'Angola' },
        { pt: 'Antígua e Barbuda', es: 'Antigua y Barbuda', en: 'Antigua and Barbuda', fr: 'Antigua-et-Barbuda' },
        { pt: 'Arábia Saudita', es: 'Arabia Saudita', en: 'Saudi Arabia', fr: 'Arabie saoudite' },
        { pt: 'Argentina', es: 'Argentina', en: 'Argentina', fr: 'Argentine' },
        { pt: 'Arménia', es: 'Armenia', en: 'Armenia', fr: 'Arménie' },
        { pt: 'Austrália', es: 'Australia', en: 'Australia', fr: 'Australie' },
        { pt: 'Áustria', es: 'Austria', en: 'Austria', fr: 'Autriche' },
        { pt: 'Azerbaijão', es: 'Azerbaiyán', en: 'Azerbaijan', fr: 'Azerbaïdjan' },
        { pt: 'Bahamas', es: 'Bahamas', en: 'Bahamas', fr: 'Bahamas' },
        { pt: 'Bangladexe', es: 'Bangladés', en: 'Bangladesh', fr: 'Bangladesh' },
        { pt: 'Barbados', es: 'Barbados', en: 'Barbados', fr: 'Barbade' },
        { pt: 'Barém', es: 'Baréin', en: 'Bahrain', fr: 'Bahreïn' },
        { pt: 'Bélgica', es: 'Bélgica', en: 'Belgium', fr: 'Belgique' },
        { pt: 'Belize', es: 'Belice', en: 'Belize', fr: 'Belize' },
        { pt: 'Benim', es: 'Benín', en: 'Benin', fr: 'Bénin' },
        { pt: 'Bielorrússia', es: 'Bielorrusia', en: 'Belarus', fr: 'Biélorussie' },
        { pt: 'Bolívia', es: 'Bolivia', en: 'Bolivia', fr: 'Bolivie' },
        { pt: 'Bósnia e Herzegovina', es: 'Bosnia y Herzegovina', en: 'Bosnia and Herzegovina', fr: 'Bosnie-Herzégovine' },
        { pt: 'Botsuana', es: 'Botsuana', en: 'Botswana', fr: 'Botswana' },
        { pt: 'Brasil', es: 'Brasil', en: 'Brazil', fr: 'Brésil' },
        { pt: 'Brunei', es: 'Brunéi', en: 'Brunei', fr: 'Brunéi' },
        { pt: 'Bulgária', es: 'Bulgaria', en: 'Bulgaria', fr: 'Bulgarie' },
        { pt: 'Burquina Fasso', es: 'Burkina Faso', en: 'Burkina Faso', fr: 'Burkina Faso' },
        { pt: 'Burundi', es: 'Burundi', en: 'Burundi', fr: 'Burundi' },
        { pt: 'Butão', es: 'Bután', en: 'Bhutan', fr: 'Bhoutan' },
        { pt: 'Cabo Verde', es: 'Cabo Verde', en: 'Cape Verde', fr: 'Cap-Vert' },
        { pt: 'Camarões', es: 'Camerún', en: 'Cameroon', fr: 'Cameroun' },
        { pt: 'Camboja', es: 'Camboya', en: 'Cambodia', fr: 'Cambodge' },
        { pt: 'Canadá', es: 'Canadá', en: 'Canada', fr: 'Canada' },
        { pt: 'Catar', es: 'Catar', en: 'Qatar', fr: 'Qatar' },
        { pt: 'Cazaquistão', es: 'Kazajistán', en: 'Kazakhstan', fr: 'Kazakhstan' },
        { pt: 'Chade', es: 'Chad', en: 'Chad', fr: 'Tchad' },
        { pt: 'Chile', es: 'Chile', en: 'Chile', fr: 'Chili' },
        { pt: 'China', es: 'China', en: 'China', fr: 'Chine' },
        { pt: 'Chipre', es: 'Chipre', en: 'Cyprus', fr: 'Chypre' },
        { pt: 'Colômbia', es: 'Colombia', en: 'Colombia', fr: 'Colombie' },
        { pt: 'Comores', es: 'Comoras', en: 'Comoros', fr: 'Comores' },
        { pt: 'Congo', es: 'Congo', en: 'Congo', fr: 'Congo' },
        { pt: 'Coreia do Norte', es: 'Corea del Norte', en: 'North Korea', fr: 'Corée du Nord' },
        { pt: 'Coreia do Sul', es: 'Corea del Sur', en: 'South Korea', fr: 'Corée du Sud' },
        { pt: 'Costa do Marfim', es: 'Costa de Marfil', en: 'Ivory Coast', fr: 'Côte d’Ivoire' },
        { pt: 'Costa Rica', es: 'Costa Rica', en: 'Costa Rica', fr: 'Costa Rica' },
        { pt: 'Croácia', es: 'Croacia', en: 'Croatia', fr: 'Croatie' },
        { pt: 'Cuba', es: 'Cuba', en: 'Cuba', fr: 'Cuba' },
        { pt: 'Dinamarca', es: 'Dinamarca', en: 'Denmark', fr: 'Danemark' },
        { pt: 'Djibuti', es: 'Yibuti', en: 'Djibouti', fr: 'Djibouti' },
        { pt: 'Dominica', es: 'Dominica', en: 'Dominica', fr: 'Dominique' },
        { pt: 'Egito', es: 'Egipto', en: 'Egypt', fr: 'Égypte' },
        { pt: 'El Salvador', es: 'El Salvador', en: 'El Salvador', fr: 'Salvador' },
        { pt: 'Emirados Árabes Unidos', es: 'Emiratos Árabes Unidos', en: 'United Arab Emirates', fr: 'Émirats arabes unis' },
        { pt: 'Equador', es: 'Ecuador', en: 'Ecuador', fr: 'Équateur' },
        { pt: 'Eritreia', es: 'Eritrea', en: 'Eritrea', fr: 'Érythrée' },
        { pt: 'Eslováquia', es: 'Eslovaquia', en: 'Slovakia', fr: 'Slovaquie' },
        { pt: 'Eslovênia', es: 'Eslovenia', en: 'Slovenia', fr: 'Slovénie' },
        { pt: 'Espanha', es: 'España', en: 'Spain', fr: 'Espagne' },
        { pt: 'Estados Unidos', es: 'Estados Unidos', en: 'United States', fr: 'États-Unis' },
        { pt: 'Estónia', es: 'Estonia', en: 'Estonia', fr: 'Estonie' },
        { pt: 'Eswatini', es: 'Esuatini', en: 'Eswatini', fr: 'Eswatini' },
        { pt: 'Etiópia', es: 'Etiopía', en: 'Ethiopia', fr: 'Éthiopie' },
        { pt: 'Fiji', es: 'Fiyi', en: 'Fiji', fr: 'Fidji' },
        { pt: 'Filipinas', es: 'Filipinas', en: 'Philippines', fr: 'Philippines' },
        { pt: 'Finlândia', es: 'Finlandia', en: 'Finland', fr: 'Finlande' },
        { pt: 'França', es: 'Francia', en: 'France', fr: 'France' },
        { pt: 'Gabão', es: 'Gabón', en: 'Gabon', fr: 'Gabon' },
        { pt: 'Gâmbia', es: 'Gambia', en: 'Gambia', fr: 'Gambie' },
        { pt: 'Gana', es: 'Ghana', en: 'Ghana', fr: 'Ghana' },
        { pt: 'Geórgia', es: 'Georgia', en: 'Georgia', fr: 'Géorgie' },
        { pt: 'Granada', es: 'Granada', en: 'Grenada', fr: 'Grenade' },
        { pt: 'Grécia', es: 'Grecia', en: 'Greece', fr: 'Grèce' },
        { pt: 'Guatemala', es: 'Guatemala', en: 'Guatemala', fr: 'Guatemala' },
        { pt: 'Guiana', es: 'Guyana', en: 'Guyana', fr: 'Guyana' },
        { pt: 'Guiné', es: 'Guinea', en: 'Guinea', fr: 'Guinée' },
        { pt: 'Guiné-Bissau', es: 'Guinea-Bisáu', en: 'Guinea-Bissau', fr: 'Guinée-Bissau' },
        { pt: 'Guiné Equatorial', es: 'Guinea Ecuatorial', en: 'Equatorial Guinea', fr: 'Guinée équatoriale' },
        { pt: 'Haiti', es: 'Haití', en: 'Haiti', fr: 'Haïti' },
        { pt: 'Holanda', es: 'Países Bajos', en: 'Netherlands', fr: 'Pays-Bas' },
        { pt: 'Honduras', es: 'Honduras', en: 'Honduras', fr: 'Honduras' },
        { pt: 'Hungria', es: 'Hungría', en: 'Hungary', fr: 'Hongrie' },
        { pt: 'Iémen', es: 'Yemen', en: 'Yemen', fr: 'Yémen' },
        { pt: 'Ilhas Marshall', es: 'Islas Marshall', en: 'Marshall Islands', fr: 'Îles Marshall' },
        { pt: 'Ilhas Maurício', es: 'Mauricio', en: 'Mauritius', fr: 'Maurice' },
        { pt: 'Ilhas Salomão', es: 'Islas Salomón', en: 'Solomon Islands', fr: 'Îles Salomon' },
        { pt: 'Índia', es: 'India', en: 'India', fr: 'Inde' },
        { pt: 'Indonésia', es: 'Indonesia', en: 'Indonesia', fr: 'Indonésie' },
        { pt: 'Irão', es: 'Irán', en: 'Iran', fr: 'Iran' },
        { pt: 'Iraque', es: 'Irak', en: 'Iraq', fr: 'Irak' },
        { pt: 'Irlanda', es: 'Irlanda', en: 'Ireland', fr: 'Irlande' },
        { pt: 'Islândia', es: 'Islandia', en: 'Iceland', fr: 'Islande' },
        { pt: 'Israel', es: 'Israel', en: 'Israel', fr: 'Israël' },
        { pt: 'Itália', es: 'Italia', en: 'Italy', fr: 'Italie' },
        { pt: 'Jamaica', es: 'Jamaica', en: 'Jamaica', fr: 'Jamaïque' },
        { pt: 'Japão', es: 'Japón', en: 'Japan', fr: 'Japon' },
        { pt: 'Jordânia', es: 'Jordania', en: 'Jordan', fr: 'Jordanie' },
        { pt: 'Kosovo', es: 'Kosovo', en: 'Kosovo', fr: 'Kosovo' },
        { pt: 'Kuwait', es: 'Kuwait', en: 'Kuwait', fr: 'Koweït' },
        { pt: 'Laos', es: 'Laos', en: 'Laos', fr: 'Laos' },
        { pt: 'Lesoto', es: 'Lesoto', en: 'Lesotho', fr: 'Lesotho' },
        { pt: 'Letónia', es: 'Letonia', en: 'Latvia', fr: 'Lettonie' },
        { pt: 'Líbano', es: 'Líbano', en: 'Lebanon', fr: 'Liban' },
        { pt: 'Libéria', es: 'Liberia', en: 'Liberia', fr: 'Liberia' },
        { pt: 'Líbia', es: 'Libia', en: 'Libya', fr: 'Libye' },
        { pt: 'Listenstaine', es: 'Liechtenstein', en: 'Liechtenstein', fr: 'Liechtenstein' },
        { pt: 'Lituânia', es: 'Lituania', en: 'Lithuania', fr: 'Lituanie' },
        { pt: 'Luxemburgo', es: 'Luxemburgo', en: 'Luxembourg', fr: 'Luxembourg' },
        { pt: 'Madagáscar', es: 'Madagascar', en: 'Madagascar', fr: 'Madagascar' },
        { pt: 'Malásia', es: 'Malasia', en: 'Malaysia', fr: 'Malaisie' },
        { pt: 'Maláui', es: 'Malaui', en: 'Malawi', fr: 'Malawi' },
        { pt: 'Maldivas', es: 'Maldivas', en: 'Maldives', fr: 'Maldives' },
        { pt: 'Mali', es: 'Malí', en: 'Mali', fr: 'Mali' },
        { pt: 'Malta', es: 'Malta', en: 'Malta', fr: 'Malte' },
        { pt: 'Marrocos', es: 'Marruecos', en: 'Morocco', fr: 'Maroc' },
        { pt: 'Maurícia', es: 'Mauricio', en: 'Mauritius', fr: 'Maurice' },
        { pt: 'Mauritânia', es: 'Mauritania', en: 'Mauritania', fr: 'Mauritanie' },
        { pt: 'México', es: 'México', en: 'Mexico', fr: 'Mexique' },
        { pt: 'Mianmar', es: 'Birmania', en: 'Myanmar', fr: 'Myanmar' },
        { pt: 'Micronésia', es: 'Micronesia', en: 'Micronesia', fr: 'Micronésie' },
        { pt: 'Moçambique', es: 'Mozambique', en: 'Mozambique', fr: 'Mozambique' },
        { pt: 'Moldávia', es: 'Moldavia', en: 'Moldova', fr: 'Moldavie' },
        { pt: 'Mónaco', es: 'Mónaco', en: 'Monaco', fr: 'Monaco' },
        { pt: 'Mongólia', es: 'Mongolia', en: 'Mongolia', fr: 'Mongolie' },
        { pt: 'Montenegro', es: 'Montenegro', en: 'Montenegro', fr: 'Monténégro' },
        { pt: 'Namíbia', es: 'Namibia', en: 'Namibia', fr: 'Namibie' },
        { pt: 'Nauru', es: 'Nauru', en: 'Nauru', fr: 'Nauru' },
        { pt: 'Nepal', es: 'Nepal', en: 'Nepal', fr: 'Népal' },
        { pt: 'Nicarágua', es: 'Nicaragua', en: 'Nicaragua', fr: 'Nicaragua' },
        { pt: 'Níger', es: 'Níger', en: 'Niger', fr: 'Niger' },
        { pt: 'Nigéria', es: 'Nigeria', en: 'Nigeria', fr: 'Nigéria' },
        { pt: 'Noruega', es: 'Noruega', en: 'Norway', fr: 'Norvège' },
        { pt: 'Nova Zelândia', es: 'Nueva Zelanda', en: 'New Zealand', fr: 'Nouvelle-Zélande' },
        { pt: 'Omã', es: 'Omán', en: 'Oman', fr: 'Oman' },
        { pt: 'Países Baixos', es: 'Países Bajos', en: 'Netherlands', fr: 'Pays-Bas' },
        { pt: 'Palau', es: 'Palaos', en: 'Palau', fr: 'Palaos' },
        { pt: 'Panamá', es: 'Panamá', en: 'Panama', fr: 'Panama' },
        { pt: 'Papua-Nova Guiné', es: 'Papúa Nueva Guinea', en: 'Papua New Guinea', fr: 'Papouasie-Nouvelle-Guinée' },
        { pt: 'Paquistão', es: 'Pakistán', en: 'Pakistan', fr: 'Pakistan' },
        { pt: 'Paraguai', es: 'Paraguay', en: 'Paraguay', fr: 'Paraguay' },
        { pt: 'Peru', es: 'Perú', en: 'Peru', fr: 'Pérou' },
        { pt: 'Polónia', es: 'Polonia', en: 'Poland', fr: 'Pologne' },
        { pt: 'Portugal', es: 'Portugal', en: 'Portugal', fr: 'Portugal' },
        { pt: 'Quénia', es: 'Kenia', en: 'Kenya', fr: 'Kenya' },
        { pt: 'Quirguistão', es: 'Kirguistán', en: 'Kyrgyzstan', fr: 'Kirghizistan' },
        { pt: 'Reino Unido', es: 'Reino Unido', en: 'United Kingdom', fr: 'Royaume-Uni' },
        { pt: 'República Centro-Africana', es: 'República Centroafricana', en: 'Central African Republic', fr: 'République centrafricaine' },
        { pt: 'República Checa', es: 'República Checa', en: 'Czech Republic', fr: 'République tchèque' },
        { pt: 'República Dominicana', es: 'República Dominicana', en: 'Dominican Republic', fr: 'République dominicaine' },
        { pt: 'Roménia', es: 'Rumania', en: 'Romania', fr: 'Roumanie' },
        { pt: 'Ruanda', es: 'Ruanda', en: 'Rwanda', fr: 'Rwanda' },
        { pt: 'Rússia', es: 'Rusia', en: 'Russia', fr: 'Russie' },
        { pt: 'Salvador', es: 'El Salvador', en: 'El Salvador', fr: 'Salvador' },
        { pt: 'Samoa', es: 'Samoa', en: 'Samoa', fr: 'Samoa' },
        { pt: 'San Marino', es: 'San Marino', en: 'San Marino', fr: 'Saint-Marin' },
        { pt: 'Santa Lúcia', es: 'Santa Lucía', en: 'Saint Lucia', fr: 'Sainte-Lucie' },
        { pt: 'São Cristóvão e Neves', es: 'San Cristóbal y Nieves', en: 'Saint Kitts and Nevis', fr: 'Saint-Christophe-et-Niévès' },
        { pt: 'São Tomé e Príncipe', es: 'Santo Tomé y Príncipe', en: 'Sao Tome and Principe', fr: 'Sao Tomé-et-Principe' },
        { pt: 'São Vicente e Granadinas', es: 'San Vicente y las Granadinas', en: 'Saint Vincent and the Grenadines', fr: 'Saint-Vincent-et-les-Grenadines' },
        { pt: 'Seicheles', es: 'Seychelles', en: 'Seychelles', fr: 'Seychelles' },
        { pt: 'Senegal', es: 'Senegal', en: 'Senegal', fr: 'Sénégal' },
        { pt: 'Serra Leoa', es: 'Sierra Leona', en: 'Sierra Leone', fr: 'Sierra Leone' },
        { pt: 'Singapura', es: 'Singapur', en: 'Singapore', fr: 'Singapour' },
        { pt: 'Síria', es: 'Siria', en: 'Syria', fr: 'Syrie' },
        { pt: 'Somália', es: 'Somalia', en: 'Somalia', fr: 'Somalie' },
        { pt: 'Sri Lanka', es: 'Sri Lanka', en: 'Sri Lanka', fr: 'Sri Lanka' },
        { pt: 'Suazilândia', es: 'Esuatini', en: 'Eswatini', fr: 'Eswatini' },
        { pt: 'Sudão', es: 'Sudán', en: 'Sudan', fr: 'Soudan' },
        { pt: 'Sudão do Sul', es: 'Sudán del Sur', en: 'South Sudan', fr: 'Soudan du Sud' },
        { pt: 'Suécia', es: 'Suecia', en: 'Sweden', fr: 'Suède' },
        { pt: 'Suíça', es: 'Suiza', en: 'Switzerland', fr: 'Suisse' },
        { pt: 'Suriname', es: 'Surinam', en: 'Suriname', fr: 'Suriname' },
        { pt: 'Tailândia', es: 'Tailandia', en: 'Thailand', fr: 'Thaïlande' },
        { pt: 'Taiuã', es: 'Taiwán', en: 'Taiwan', fr: 'Taïwan' },
        { pt: 'Tajiquistão', es: 'Tayikistán', en: 'Tajikistan', fr: 'Tadjikistan' },
        { pt: 'Tanzânia', es: 'Tanzania', en: 'Tanzania', fr: 'Tanzanie' },
        { pt: 'Timor-Leste', es: 'Timor Oriental', en: 'Timor-Leste', fr: 'Timor oriental' },
        { pt: 'Togo', es: 'Togo', en: 'Togo', fr: 'Togo' },
        { pt: 'Tonga', es: 'Tonga', en: 'Tonga', fr: 'Tonga' },
        { pt: 'Trindade e Tobago', es: 'Trinidad y Tobago', en: 'Trinidad and Tobago', fr: 'Trinité-et-Tobago' },
        { pt: 'Tunísia', es: 'Túnez', en: 'Tunisia', fr: 'Tunisie' },
        { pt: 'Turcomenistão', es: 'Turkmenistán', en: 'Turkmenistan', fr: 'Turkménistan' },
        { pt: 'Turquia', es: 'Turquía', en: 'Turkey', fr: 'Turquie' },
        { pt: 'Tuvalu', es: 'Tuvalu', en: 'Tuvalu', fr: 'Tuvalu' },
        { pt: 'Ucrânia', es: 'Ucrania', en: 'Ukraine', fr: 'Ukraine' },
        { pt: 'Uganda', es: 'Uganda', en: 'Uganda', fr: 'Ouganda' },
        { pt: 'Uruguai', es: 'Uruguay', en: 'Uruguay', fr: 'Uruguay' },
        { pt: 'Usbequistão', es: 'Uzbekistán', en: 'Uzbekistan', fr: 'Ouzbékistan' },
        { pt: 'Vanuatu', es: 'Vanuatu', en: 'Vanuatu', fr: 'Vanuatu' },
        { pt: 'Vaticano', es: 'Vaticano', en: 'Vatican', fr: 'Vatican' },
        { pt: 'Venezuela', es: 'Venezuela', en: 'Venezuela', fr: 'Venezuela' },
        { pt: 'Vietname', es: 'Vietnam', en: 'Vietnam', fr: 'Vietnam' },
        { pt: 'Zâmbia', es: 'Zambia', en: 'Zambia', fr: 'Zambie' },
        { pt: 'Zimbabué', es: 'Zimbabue', en: 'Zimbabwe', fr: 'Zimbabwe' },
    ];